--
-- PostgreSQL database dump
--

\restrict bKvYtXc8xk3eSEkOk0Uy6pakiAQyruJ5HQjaMeC98zs8umSXnKgdY6YnZ9Oc4AS

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 16.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: collection_vacancies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collection_vacancies (
    id integer NOT NULL,
    collection_id integer NOT NULL,
    vacancy_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: collection_vacancies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collection_vacancies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_vacancies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collections (
    id integer NOT NULL,
    name text NOT NULL,
    parameters jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employers (
    id integer NOT NULL,
    hhru_id bigint,
    name text,
    description text,
    industry_type text,
    site_url text,
    area text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: employers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: vacancies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vacancies (
    id integer NOT NULL,
    employer_id integer,
    hhru_id bigint,
    name text,
    description text,
    area text,
    experience text,
    employment_form text,
    salary_from bigint,
    salary_to bigint,
    salary_currency text,
    work_format text[],
    professional_roles text[],
    key_skills text[],
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: vacancies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vacancies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vacancies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_vacancies collection_vacancies_collection_id_vacancy_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_vacancies
    ADD CONSTRAINT collection_vacancies_collection_id_vacancy_id_key UNIQUE (collection_id, vacancy_id);


--
-- Name: collection_vacancies collection_vacancies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_vacancies
    ADD CONSTRAINT collection_vacancies_pkey PRIMARY KEY (id);


--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);


--
-- Name: employers employers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: vacancies vacancies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacancies
    ADD CONSTRAINT vacancies_pkey PRIMARY KEY (id);


--
-- Name: collection_vacancies_collection_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX collection_vacancies_collection_id_index ON public.collection_vacancies USING btree (collection_id);


--
-- Name: collection_vacancies_vacancy_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX collection_vacancies_vacancy_id_index ON public.collection_vacancies USING btree (vacancy_id);


--
-- Name: collections_created_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX collections_created_at_index ON public.collections USING btree (created_at);


--
-- Name: employers_created_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX employers_created_at_index ON public.employers USING btree (created_at);


--
-- Name: employers_hhru_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX employers_hhru_id_index ON public.employers USING btree (hhru_id);


--
-- Name: vacancies_created_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vacancies_created_at_index ON public.vacancies USING btree (created_at);


--
-- Name: vacancies_employer_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vacancies_employer_id_index ON public.vacancies USING btree (employer_id);


--
-- Name: vacancies_hhru_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX vacancies_hhru_id_index ON public.vacancies USING btree (hhru_id);


--
-- PostgreSQL database dump complete
--

\unrestrict bKvYtXc8xk3eSEkOk0Uy6pakiAQyruJ5HQjaMeC98zs8umSXnKgdY6YnZ9Oc4AS



--
-- PostgreSQL database dump
--

\restrict fZZMvPOzvhqE6cnFgDqFSHkFDoICLzciFpbsOIR9K6htn9bu0tF49gUC1edgwgJ

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 16.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.schema_migrations VALUES ('20250914161411_create_employers.rb');
INSERT INTO public.schema_migrations VALUES ('20250915150552_create_vacancies.rb');
INSERT INTO public.schema_migrations VALUES ('20250916154000_create_collections.rb');
INSERT INTO public.schema_migrations VALUES ('20250917130539_create_collection_vacancies.rb');


--
-- PostgreSQL database dump complete
--

\unrestrict fZZMvPOzvhqE6cnFgDqFSHkFDoICLzciFpbsOIR9K6htn9bu0tF49gUC1edgwgJ

