--
-- PostgreSQL database dump
--

\restrict 2W41raKqBN0b5EkGkfOmGTqUGOqpGgchzXO677Yvx2nz40jEPXRxBKPWQ4EPdbC

-- Dumped from database version 14.11 (Homebrew)
-- Dumped by pg_dump version 16.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: employers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employers (
    id integer NOT NULL,
    hhru_id bigint,
    name text,
    description text,
    industry_type text,
    site_url text,
    area text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: employers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: vacancies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vacancies (
    id integer NOT NULL,
    employer_id integer,
    hhru_id bigint,
    name text,
    description text,
    area text,
    experience text,
    employment_form text,
    salary_from bigint,
    salary_to bigint,
    salary_currency text,
    work_format text[],
    professional_roles text[],
    key_skills text[],
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: vacancies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vacancies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vacancies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employers employers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: vacancies vacancies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacancies
    ADD CONSTRAINT vacancies_pkey PRIMARY KEY (id);


--
-- Name: employers_created_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX employers_created_at_index ON public.employers USING btree (created_at);


--
-- Name: employers_hhru_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX employers_hhru_id_index ON public.employers USING btree (hhru_id);


--
-- Name: vacancies_created_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vacancies_created_at_index ON public.vacancies USING btree (created_at);


--
-- Name: vacancies_employer_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vacancies_employer_id_index ON public.vacancies USING btree (employer_id);


--
-- Name: vacancies_hhru_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX vacancies_hhru_id_index ON public.vacancies USING btree (hhru_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2W41raKqBN0b5EkGkfOmGTqUGOqpGgchzXO677Yvx2nz40jEPXRxBKPWQ4EPdbC



--
-- PostgreSQL database dump
--

\restrict Tc9qcj32YJfLj7kL6E05Ko63MqRCSnuMyYpkfSiYyvzL5jffx1Jkqt87HqVim0t

-- Dumped from database version 14.11 (Homebrew)
-- Dumped by pg_dump version 16.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.schema_migrations VALUES ('20250914161411_create_employers.rb');
INSERT INTO public.schema_migrations VALUES ('20250915150552_create_vacancies.rb');


--
-- PostgreSQL database dump complete
--

\unrestrict Tc9qcj32YJfLj7kL6E05Ko63MqRCSnuMyYpkfSiYyvzL5jffx1Jkqt87HqVim0t

